### ISSUE TITLE
Version of recaptcha for e107 v0.7.25

### ISSUE THREAD

**Issue by brynnneilson** [Jimmi08/recaptcha#1]
I'm still running many old e107 sites on 0.7.25. Can I pay you to make a version of NoCaptcha ReCaptcha for e107 0.7.25? You can still release it as open source.

brynn :-)

**Comment by Jimmi08** [comment]
Hi,
I could try to do it. Not sure if this can be done via plugin. 

I suppose you are using php 5.  

Do you use 0.7.25 from here?
https://sourceforge.net/projects/e107/files/e107/
because there is Russian version too. 

I have still one 1.0.4 site, so I could test it there too.

We will see.

**Comment by Jimmi08** [comment]
Ok, it's possible only on contact and signup.php

![image](https://user-images.githubusercontent.com/5429548/44096425-82d96538-9fdb-11e8-81e1-082cf4c395e7.png)

It's not centered in Firefox, there is some browser issue.

I am not able to use it on login.php because templates are loaded after  HEADERF, so I am not able to changed them in e_meta.php. The same for login_menu.

I solved this without changing core sef image handler and without JQuery! 

![image](https://user-images.githubusercontent.com/5429548/44096718-3b217ffe-9fdc-11e8-9731-1b155a16f4f1.png)

After more testing and cleaning code I will put it for download.

**Comment by Jimmi08** [comment]
Added.

You can download it directly from here:  
https://www.e107.sk/download/27/recaptcha-for-0-7-25-and-1-0-4-e107-version
Registration is not needed. 

Test it, if anything,  prefered support is via forum.  

Of course, donation is always welcome, but it's not condition.
